sudo: required
services:
    - docker

before_install:
    - docker build -t kissta/fibonacci_seq -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true kissta/fibonacci_seq npm test -- --coverage

after_success:
    - docker build -t kissta/fibonacci-client  ./client
    - docker build -t kissta/fibonacci-nginx  ./nginx
    - docker build -t kissta/fibonacci-server ./server
    - docker build -t kissta/fibonacci-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push to dockerhub
- docker push kissta/fibonacci-client
- docker push kissta/fibonacci-nginx
- docker push kissta/fibonacci-server
- docker push kissta/fibonacci-worker

